In [ ]:
import numpy as np
import cv2

gb = cv2.getGaborKernel((21, 21), 2.5, 0, 10, 1, 0)

In [ ]:
from matplotlib import pyplot as plt
plt.imshow(gb, cmap='hot', interpolation='nearest')
plt.show()

In [ ]:
import math

def gabor(size, m, n):
    filters = np.zeros((m, n), np.ndarray)

    for M in range(m):
        for N in range(n):
            omega = ((math.pi / 2) * (math.sqrt(2) ** (-M + 1)))
            theta = N / n * math.pi
            sigma = math.pi / omega
            lambd =  2 * math.pi / omega
            filters[M][N] = cv2.getGaborKernel(size, sigma, theta, lambd, 1, 0)

    return filters

In [ ]:
gbs = gabor((11, 11), 5, 10)

In [ ]:
fig, axes = plt.subplots(nrows=5, ncols=10)

for i in range(5):
    for j in range(10):
        axes[i, j].imshow(gbs[i][j], cmap='hot', interpolation='nearest')
        axes[i, j].axis('off')

In [ ]:
from fb import *
fb = bases_list(11, 6)
print(fb.shape)

In [ ]:
plt.imshow(fb.numpy()[-2].reshape((11, 11)), cmap='hot', interpolation='nearest')

In [ ]:
6 // 2

In [ ]:
from model import get_gabor_bases
get_gabor_bases(11, 6).shape

In [ ]:
import data
dt = data.CIFAR10DataModule()

In [ ]:
dt.prepare_data()

In [2]:
import torch
x = torch.arange(2*4).view(2, 4)
print(x)
print(x.view(4, 2))
print(x.permute(1, 0))
print(x.transpose(1, 0))

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])
tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])


In [32]:
x = torch.randn(2, 2, 4, 4)
print(x)
x = torch.nn.functional.unfold(x, 2, padding=0)
print(x.transpose(-1, -2).view(2, 3, 3, 2, -1))
print(x[None, None].permute(2, 3, 3, 2, -1))

tensor([[[[-2.0503, -0.4404, -0.4114,  0.4653],
          [ 0.5350,  0.5561,  1.4243,  1.3563],
          [ 0.8219, -0.6184, -0.3024, -1.6516],
          [ 0.3067,  0.5065, -0.2464,  1.1752]],

         [[-1.2896, -1.1360,  0.8746,  2.8707],
          [-1.0344, -1.6423,  1.0631, -0.5996],
          [-0.7735, -1.6041, -0.7816, -0.0622],
          [ 0.6500, -0.7270, -1.1254,  0.7736]]],


        [[[-0.8709, -0.0187, -0.9086, -1.4792],
          [ 1.7138,  0.1830, -1.5960,  0.8265],
          [ 1.5786, -1.5769, -0.2699,  0.7664],
          [ 1.0048,  0.4769, -0.8448,  0.2598]],

         [[ 1.5563, -0.0698, -0.3073,  0.4236],
          [-0.6305, -0.7296, -0.1744, -1.0256],
          [ 0.5227, -0.9579,  0.1254, -0.0491],
          [-0.6453,  0.5264,  1.2212, -1.1934]]]])
tensor([[[[[-2.0503, -0.4404,  0.5350,  0.5561],
           [-1.2896, -1.1360, -1.0344, -1.6423]],

          [[-0.4404, -0.4114,  0.5561,  1.4243],
           [-1.1360,  0.8746, -1.6423,  1.0631]],

          [[-0.4114, 

RuntimeError: permute(): duplicate dims are not allowed.

In [29]:
x1 = torch.randn(2, 6, 1)
x2 = torch.randn(1, 6, 2)
(x1 * x2).shape

torch.Size([2, 6, 2])